#!/bin/sh

if [ ! -f $HOME/.config/fortune/fortune.txt ]; then
mkdir -p $HOME/.config/fortune
  sshfs -o reconnect -p 8022 jularthus@jularthus.fr:/home/jularthus/AuCoin/fortune ~/.config/fortune ;
fi
touch $HOME/.fortune ;
killall polybar ;
nohup polybar >/dev/null 2>&1 &
